### ISSUE TITLE
Improve page titles

### ISSUE THREAD

**Issue by wfdd** [everypolitician/viewer-sinatra#10130]
The title of http://everypolitician.org/cyprus/ is simply 'EveryPoltician', while in http://everypolitician.org/cyprus/house-of-representatives/term-table/2011.html it's just the date range.  These could be changed to '_country_ – EveryPolitician' and '_term_ – _country_ – EveryPolitician' or something of the sort.

**Comment by wfdd** [comment]
Okay, this has already been reported at everypolitician/everypolitician#409.  Should I be opening new issues here or there?

**Comment by tmtmtmtm** [comment]
Your initial instinct was correct. Issues to do with the site are better here. Every so often we'll move issues like https://github.com/everypolitician/everypolitician/issues/409 to this repo instead, but Github doesn't make that easy, so they have a tendency to just languish over there for a while.

**Comment by tmtmtmtm** [comment]
The two tickets are a little different, in that this one seems to be about the actual HTML `title`, whereas the other is about the `header` section of the page. That one is a little more complex, as it is spread over several visible elements, and we want to minimise the duplication where the name the term also contains the name of the legislature[1]. So I'll leave that one open as also needing some design input. But this one was simple to fix, so I've done so :)

Thanks for the report!


[1] For Cyprus I'm unaware of the terms actually having names or even being numbered (e.g. 10th Parliament), so we just fall back on using the dates. But happy to change that if there's something better we should be doing.

**Comment by wfdd** [comment]
Thanks!  Advance apologies for the pedantry that is to follow, but the dash between the country and the house is an em dash, whereas the one between the house and the term is actually a hyphen - the two are of course impossible to tell apart in monospace :(

----

The terms are numbered in Greek numerals (the term that just ended was the "Ι"....th?), but they're hardly ever referred to by their number.
