### ISSUE TITLE
Change twitter links

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#10263]
The `meta` section of each page includes:

`<meta name="twitter:site" content="@mysocietyIntl" />`

But that account has been closed for a while now.

**Comment by tmtmtmtm** [comment]
@davewhiteland do you think we should we link to the bot account instead?

**Comment by davewhiteland** [comment]
Yes effectively that _is_ the EveryPolitician twitter account isn't it? (unless we really needed another because that bot-point-of-view gets in the way of serious exchanges)

**Comment by tmtmtmtm** [comment]
I think it's fair enough to use that for now. @davewhiteland you want to make the change?

**Comment by davewhiteland** [comment]
Closed by f38e9197458c62a7a12192636cfa6e4da035394d
