### ISSUE TITLE
Can't ctrl/cmd-A in search box

### ISSUE THREAD

**Issue by wfdd** [everypolitician/viewer-sinatra#10276]
I'm assuming there's a two-way event listener that updates the search box from the address bar, so the instant I press cmd-A, keyup is detected, the new search term is pushed to the address bar and immediately pulled back into the search box, resetting my cursor.

**Comment by tmtmtmtm** [comment]
@zarino, can you spot a quick fix for this?

**Comment by zarino** [comment]
@wfdd is right – we’re binding an listener to the `keyup` event in that search box, which then overwrites the text input with the current search term after a short delay:

https://github.com/everypolitician/viewer-sinatra/blob/d0aaaa40f708483c9f374d2ef98e67a562e4658e/public/javascript/ep-card-filter.js#L186-L190

I think the simplest fix here is to only change the text input value if it *needs* to be changed. (ie: add another condition to [`this.setSearch`](https://github.com/everypolitician/viewer-sinatra/blob/d0aaaa40f708483c9f374d2ef98e67a562e4658e/public/javascript/ep-card-filter.js#L147-L157) that bails out early if `newSearch === newSearch`).

**Comment by zarino** [comment]
Note to self: I wonder whether we could bind to the `input` event here instead.
