### ISSUE TITLE
Move the 'download' information to a separate page

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#10523]
We currently offer 'Download' links from two different pages (the country page, and an individual term page). They've evolved separately from each other, and are confusing in several key ways. To make them more understandable we need to add more text to them, but this is already unwieldy, and we certainly don't have room to add _more_ options (e.g. the names file, or other types of downloads; explaining the difference between the current *term* (potentially with multiple memberships for people) and the current *members*, etc.).

So, instead, let's add a separate Downloads page for each country, listing and explaining all the different options, and either linking to or transcluding part of the docs explaining things like rawgit, fetching by sha, keeping up to date via webhooks etc.

**Comment by davewhiteland** [comment]
This now implemented:
First in #10637 which introduced a bug (in the sinatra &rarr; wget &rarr; gh-pages process), fixed in quick succession by two slightly ugly PRs: #11632 and #11636
