### ISSUE TITLE
Harmonise styles with Everypolitician

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#120]
Some of the styles used in https://github.com/mysociety/everypolitician don't exist here, so we can't currently replicate how those pages work.

If we could recreate those pages here too, then we'd have more flexibility in how we generate the resulting site (currently we're splitting it across two different gh-pages repos)

**Comment by zarino** [comment]
The two sites are being merged (with the majority of the current EP jekyll site being discarded) so the styles no longer need "harmonising" – we'll just pull over the few original EP styles that we need, as and when we do the merge.

See https://github.com/everypolitician/viewer-sinatra/issues/279
