### ISSUE TITLE
Flexbox wrapping doesn’t work in Safari

### ISSUE THREAD

**Issue by zarino** [everypolitician/viewer-sinatra#127]
None of the wrapping declarations are being accepted by Safari.

This causes the person/party lists to just extend off the screen.

![screen shot 2015-05-01 at 16 17 51](https://cloud.githubusercontent.com/assets/739624/7432190/d817de7e-f01d-11e4-967e-877b51a30119.png)

First port of call: check that `-webkit-box-wrap` is the right thing to use, and that `wrap` is a valid value for it.

**Comment by zarino** [comment]
HT to @davewhiteland for spotting this!

**Comment by dracos** [comment]
It works here (Safari 7) if I change it to `-webkit-flex-wrap`

**Comment by dracos** [comment]
Annoyingly (saw this myself this morning) this also applies to Android browser 4.1/4.3, about 4% browsers according to caniuse, as it supports flex but not flex wrap. There's no solution but to sniff user agent string (which I think is justified for a no longer maintained browser), you need to look for a webkit version of < 537, and Android version < 4.4.

**Comment by dracos** [comment]
If it's not a static site, you could do something like this to deal with it server side:
```
ua = get_header("HTTP_USER_AGENT")
m = re.search('Android ([\d.]+).*?AppleWebKit/([\d.]+)', ua)
if m:
    android, webkit = map(float, m.groups())
    if android < 4.4 and webkit < 537:
        print "<style>don't use flex for the list</style>"
        add_header("X-CSS-Fix", "android4.3-flex")
        append_header("Vary", "X-CSS-Fix")
```
If static site, then I guess would have to non-ideally be in JavaScript, and something like:
```
var m = window.navigator.userAgent.match(/Android ([\d.]+).*?AppleWebKit\/([\d.]+)/);
var is_old_android = (m && m[1] < 4.4 and m[2] < 537);
```

**Comment by zarino** [comment]
Typically you’d solve this by using something like https://modernizr.com to detect a set of features and add a class to the html element if it's available in the user's browser.

**Comment by dracos** [comment]
Ah, Modernizr only added flex-wrap detection this Friday :) Otherwise I'd have suggested it, I was using it only last week on FixMyStreet. Tested, seems to work, and will additionally support old Firefox/Chrome/Safaris. Though 4k library, seems bit big for just that check, wonder what else it has in it. PR at #662.
