### ISSUE TITLE
Is this data incorrect?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#130]
Add a link at the bottom of every page to the Contributing page.

**Comment by MyfanwyNixon** [comment]
Copy is at https://docs.google.com/document/d/1c6k1c_Cd5Gj1evw5rQMlh9QkFO-3zXTtGOBXuFkDAgY/edit

**Comment by tmtmtmtm** [comment]
Thank @MyfanwyNixon — those are (mostly) all live now. I've left the more Technical page for now, as it'll require more detailed work from me. The only other thing still outstanding for now (unless you see any problems with the live version) is a line at the bottom of an actual data page (like http://everypolitician.org/scotland/parliament/term-table/4.html) that tells people what to do if they see anything incorrect or missing.

**Comment by MyfanwyNixon** [comment]
Good.
That line could read:

> Anything wrong? If you've spotted an error or the data is incomplete, [here's how to get that fixed](http://everypolitician.org/contribute.html).

**Comment by tmtmtmtm** [comment]
Thanks @MyfanwyNixon — now live. I probably won't get a chance to do anything on the more technical documentation for a couple of days now, so perhaps best to leave that until @davewhiteland gets back, and then try to work on that again together.
