### ISSUE TITLE
One download page per legislature

### ISSUE THREAD

**Issue by zarino** [everypolitician/viewer-sinatra#13599]
# Problem

We currently have a download page per country, but all of the download options are separated by legislature. This has a few drawbacks:

* Only the first legislature is visible on pageload, and as we add more historical data to EP, the legislatures after it will only get further down the page. On first page load, it's not obvious at all that the page contains data for more than one legislature.
* The need to pass a legislature name and a term id to the download page has resulted in somewhat overcomplicated code like https://github.com/everypolitician/viewer-sinatra/pull/12987

# Proposal

Create a download page per legislature. 

<del>Link between them via the new tab component introduced in https://github.com/everypolitician/viewer-sinatra/issues/13598.</del> Broken into separate issue: #15240 

# Acceptance Criteria

Clicking the "Download data" button on a legislature’s term_table page, should take me to a download page showing *only* the legislature I came from.

<del>In addition, if the legislature has lots of historical data, the data for the term I came from should be highlighted above any others.</del> Exists as separate issue: #14427

# Not Required

n/a

# Prerequisites

Having https://github.com/everypolitician/viewer-sinatra/pull/13598 merged would give us a tab component we could re-use for the navigation between legislature download pages. (Also useful as an above-the-fold way of signposting that we *even have* data for other legislatures in the same country).

# Related Issues

Came up as a solution to https://github.com/everypolitician/viewer-sinatra/pull/12987

# Due Date

n/a

# Design?

Will need some design time, to lay out the new single-legislature download pages.

# Text?

n/a

# Bloggable?

n/a

**Comment by tmtmtmtm** [comment]
Done
