### ISSUE TITLE
Test for suitable version of html-tidy

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#15573]
# Problem

The html-tidy tests fail if you have too old a version of html-tidy

# Proposed Solution

Make the skip check (which currently only tests for `which tidy` being true) more robust.

# Acceptance Criteria

Minimal acceptance is that the tests no longer fail on @tmtmtmtm's laptop!

# Not Required

# Prerequisites

# Related Issues

# Due Date

# Design?

# Text?

# Bloggable?

**Comment by chrismytton** [comment]
Looks like the easiest way to do this will be to check for some expected behaviour (thanks for the suggestion @tmtmtmtm!)

The following command should produce no output and should have a `0` exit status:

```
echo '<!DOCTYPE html><title>Test</title><body><header>Test</header>' | tidy -eq
```
