### ISSUE TITLE
Ask people what data we should gather for each country

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#15589]
# Problem

We want to add a lot more data (and not  about who politicians are, but also what they do). But there's a _lot_ of data to gather, for a _lot_ of countries, and we need to find some way to prioritise.
# Proposed Solution

Ask visitors to the site what they'd like to see us add (ideally because they'd actually like to **use** it)

For example, when viewing a page for a country, we ask them "Would you like to see more data for this country/legislature?"

Capture, somewhere, which ones get 'voted' for like this.

Preferably, we could also let them sign up to be notified when we add more.

Ideally, we'd let them say what types of data they'd like us to prioritise importing: possibilities include biographical information, contact details, social media profiles, political history, education history, voting records, attendance records, committee memberships, speeches, bill authorship/sponsorship, promises made, income + asset declarations, etc…)

As well as gaining lots of potentially useful information, this would also help signal that we're actively adding new data, and want to be much more than what we currently have.
# Acceptance Criteria

Minimal version: we get a list of 'votes' for each country/legislature.

Preferable: we get individual results (with optional email addresses)

Ideal: We get detail on what data they want, and why.
# Not Required

We don't need to store/gather this information in any specific way, at least not at first. If we happen to start getting LOTS of people telling us what they want, then we might want to look at some structured way of storing it, but let's leave that until we need it.
# Prerequisites
# Related Issues
# Due Date

Ideally before Mozfest.
# Design?

Preferably!
# Text?
# Bloggable?

**Comment by zarino** [comment]
@tmtmtmtm Would you be happy to do this via Google Forms for now? So, something like:

* Banner on legislature pages, encouraging people to **click here** if they want us to collect more data for this legislature.
* Button in banner leads to the Google Form, hopefully styled in EveryPolitician colours so it doesn’t look too alien.
* Responses get saved to a Google Sheet.
* Respondent is sent back to everypolitician.org (or maybe we just open the Google Form in a new tab?)

**Comment by tmtmtmtm** [comment]
@zarino: sure, that sort of thing could work well.

**Comment by JenMysoc** [comment]
If you also restrict what answers people can give (eg don't let them just write free text) then we can get graphs to show us the most popular countries/types of data

**Comment by zarino** [comment]
@JenMysoc @tmtmtmtm: We can go ahead and do the banner on the legislature pages, while you think about which questions you want to ask people. I'll investigate whether there’s a simple way to redirect people back to the page they started on when they’re done with the survey, but if not, opening in a new tab is the next best thing.

**Comment by zarino** [comment]
There’s a work-in-progress PR here with some styling: https://github.com/everypolitician/viewer-sinatra/pull/15590

**Comment by tmtmtmtm** [comment]
Closed by #15590
