### ISSUE TITLE
Move/Tidy the Download buttons

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#174]
At the moment the download buttons for JSON & CSV float left and right slightly oddly — I suspect they'd look better if grouped closer together.

It's probably also worth moving them elsewhere on the page. On unicameral parliaments they take up quite a lot of space in quite an odd manner (on Bicameral ones the house switcher will be in the same place), and the positioning also implies that you're simply downloading a list of members (which is more true for the CSV, but less so for the JSON).

**Comment by zarino** [comment]
Ah! I didn't realise the JSON file contained more than just the members. Yes, in that case it makes more sense to move the download links somewhere else.

@tmtmtmtm: Given the primarily geeky nature of the site's audience right now, how about putting download links near the top of the page, where the term name and previous/next term navigation is?

**Comment by tmtmtmtm** [comment]
@zarino sure — go for it, and let's see how it all hangs together.

**Comment by tmtmtmtm** [comment]
This version was done. #370 is about splitting them up further.
