### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by wrightmartin** [everypolitician/viewer-sinatra#279]
- Make it look more like a mySociety project
- Incorporate the brand @wrightmartin started working on

![every-p](https://cloud.githubusercontent.com/assets/2292925/8234260/c97fb992-15d2-11e5-9a7d-1466d404ca7b.png)

### Wireframe below

![img_5717 1](https://cloud.githubusercontent.com/assets/2292925/8234226/8cb0eebe-15d2-11e5-9442-d687367b8e03.jpg)

**Comment by tmtmtmtm** [comment]
We really need a favicon for the site too — not sure if that will automatically come out of this work —  or should we open a separate ticket for that?

**Comment by zarino** [comment]
@tmtmtmtm: new ticket please!

**Comment by zarino** [comment]
I've started work on this ticket in branch: [issues/279-new-homepage](https://github.com/everypolitician/viewer-sinatra/compare/issues/279-new-homepage?expand=1)

**Comment by zarino** [comment]
Ok, pull request here: https://github.com/everypolitician/viewer-sinatra/pull/303

Things, aside from that pull request, that still need doing:

* Proper text content for the bottom half of the homepage
* Wiring up the search box so it actually takes you to the country pages
* Logo (see #299)
* mySociety colours for buttons etc

**Comment by zarino** [comment]
The pull request (#303) has been merged, and tickets opened for the remaining tasks:

* Explanatory text for the homepage – #308 
* Making the search box take you to country pages – #307 
* Standardising the list of countries in the search box – #306 
* EveryPolitician logo – #299
