### ISSUE TITLE
Use customised country list on new homepage

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#306]
The search box on the new homepage (#303) uses its own list of countries that differs from ours. Harmonise these.

**Comment by zarino** [comment]
The autocomplete works best when it's provided with three pieces of information per country:

1. The country's "display name", eg: "Congo-Brazzaville"
2. The country's ISO 3166-1 alpha-2 code, eg: "CG"
3. Any other words that make up common names for the country, eg: "Republic Congo République West"

Items 2 and 3 are never shown to the user, but they *are* matched against user input, so typing "Repu…" will bring up "Congo-Brazzaville", for example.

Do we already have this data for the countries in EveryPolitician?

**Comment by tmtmtmtm** [comment]
The `countries.json` file (that you used when building the map) includes the first two (though note that in a few cases it's ISO 3166-2, rather than 3166-1). We don't have the third, though if there were another JSON file somewhere keyed by the ISO code, it would be trivial to lookup by than when building the autocomplete.

**Comment by zarino** [comment]
Further to discussion this morning, a new .json file containing *all the legislatures we might potentially cover in future* (including ones we already cover) would be great, looking like:

```json
{
  "congo-brazzaville": {
    "displayName": "Congo-Brazzaville",
    "allNames": "congo brazzaville republic of congo"
  },
  "france": {
    "displayName": "France",
    "allNames": "france"
  },
  "uk": {
    "displayName": "UK",
    "allNames": "uk united kingdom great britain england scotland wales"
  }
}
```

Where the keys in the main object are the URL slugs you currently use (or *will* use once the country is added to your dataset).

It may be that we want to drop certain common words from the "allNames" string – like "People's", "Democratic", and even "Republic" – to avoid surprising results (see https://github.com/everypolitician/viewer-sinatra/pull/303#issuecomment-114562483). But I'm happy for them to be left in for now, if that's less contentious.
