### ISSUE TITLE
New Homepage: Selecting a country should do something

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#307]
Either go to the relevant country homepage, or explain that we don't have data yet (and how to help)

**Comment by zarino** [comment]
I was imagining that the autocomplete would just always send the user to a page like `everypolitician.com/country/cg` (using the country's 2-letter ISO code or something) and then that page would either show all the data for that country, or show a message about not having any data and how you can help.

**Comment by tmtmtmtm** [comment]
The current convention is to just have them at `/country-name`, rather than `/country/code`. I think it's better to have the full name, just for nicer URLs generally, and presumably also for SEO stuff. But if we're going to change the URL structure now is definitely the time to do so.

I've opened #358 to handle the case of going to a page for a country that doesn't exist yet, so if you're doing anything with this, feel free to just assume that that will work.

**Comment by tmtmtmtm** [comment]
#358 is now live.
