### ISSUE TITLE
Split the Download buttons

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#370]
Currently we have download buttons on the Term Table page for both CSV and JSON:

![screen shot 2015-07-08 at 10 26 20](https://cloud.githubusercontent.com/assets/57483/8567293/21c927d0-255c-11e5-898f-eb19af1770b0.png)

However, these are are for conceptually different things: the CSV is only for the term you're currently viewing, whereas the JSON is for the legislature as a whole. 

If we had a separate page for each legislature, then it would make sense to put the JSON download button at the bottom of that (similarly to the one to `countries.json` on the list of countries page), but currently we just group all of them on the country page (as right now most countries only have a single legislature listed anyway). So we should probably move the JSON download to there.

**Comment by zarino** [comment]
> If we had a separate page for each legislature

Don't we already have that? eg: http://data.everypolitician.org/uk/

![screen shot 2015-07-09 at 12 25 20](https://cloud.githubusercontent.com/assets/739624/8594093/976196f6-2635-11e5-8ad9-5d32b5bda6fb.png)

**Comment by tmtmtmtm** [comment]
@zarino: that's the page for the UK, not for the House of Commons. Compare http://data.everypolitician.org/australia/
