### ISSUE TITLE
Visually distinguish countries we have data for on homepage search box

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#386]
The new search box should highlight the countries we do actually have information for, rather than the user having to go through to a page that says "Sorry, nothing here".  (Though we should still have that page, so that we can explain how people can help, etc.)

**Comment by tmtmtmtm** [comment]
A super-hacky way to do this would be to add a visually distinguishing symbol to the end of the name of each relevant country in `world.json`:

![screen shot 2015-07-09 at 16 48 57](https://cloud.githubusercontent.com/assets/57483/8599826/8214c0f0-265a-11e5-8c54-9c4e1498a4b6.png)

But I'm guessing @zarino will have a much better suggestion…

**Comment by zarino** [comment]
Probably something like:

![ticks](https://cloud.githubusercontent.com/assets/739624/8600085/edaae424-265b-11e5-9cdc-e8e8f2bd97b7.png)

Although, I'm not sure whether, whatever the icon is, people will know what it means. Maybe we should just *show* people:

![words](https://cloud.githubusercontent.com/assets/739624/8600161/5d658bde-265c-11e5-9ae2-fd3b6c8595ff.png)

**Comment by tmtmtmtm** [comment]
Ooh, I do like that second one.

**Comment by tmtmtmtm** [comment]
@zarino: `countries.json` now has a `person_count` [field per legislature](https://github.com/everypolitician/everypolitician-data/blob/master/countries.json#L14), that could be fairly trivially summed to create the "918 people" etc displayed above. Is it a fairly easy job to inject that into the list, or does it require quite a bit of fiddling?

**Comment by zarino** [comment]
@tmtmtmtm – it'll require fiddling.

**Comment by tmtmtmtm** [comment]
OK. No immediate rush on it; I'll add it to the design spreadsheet for estimation etc.

**Comment by zarino** [comment]
I've done the styling and javascript for this in #769. Just needs someone to pass the right person counts from `app.rb` into the template.
