### ISSUE TITLE
Don't show "Area" column where none exist

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#446]
Where a country (eg Aruba) explicitly has no constituencies (as distinct from us just not knowing them), we should remove the Area column.

**Comment by zarino** [comment]
Since the table has been replaced with individual cards, the "area" attribute for a person is only shown if that person has an area set:

https://github.com/everypolitician/viewer-sinatra/blob/ecc5fbafdab10b1a9445de54db48363b4a862849/views/term_table.erb#L170
