### ISSUE TITLE
CSV and JSON downloads have unhelpful Content-Type headers

### ISSUE THREAD

**Issue by mhl** [everypolitician/viewer-sinatra#474]
A limitation of downloading data from raw.githubusercontent.com is that both CSV and JSON files are served as `Content-Type: text/plain`. Ideally, they should be served from one of our own servers where we can correctly set the content types to: `text/csv` and `application/json` and add a useful `Content-Disposition` header. (I think CSV should be downloaded with `Content-Disposition: attachment`, for example.)

**Comment by tmtmtmtm** [comment]
#197 has been on the "Do as soon as someone asks for it" list for quite some time, so I've now implemented that. They files are now served from rawgit.com, which correctly uses `text/csv` and `application/json` (and is what we already [suggest](http://everypolitician.org/repo_structure.html) everyone else uses…)

It doesn't add a Content-Disposition header, though I was under the impression that Content-Disposition was generally believed to be a Bad Thing outside of email, anyway.
