### ISSUE TITLE
Update politician-image-proxy daily

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/viewer-sinatra#530]
(Migrated from https://github.com/everypolitician/app-manager/issues/23)

Currently the image-proxy gets updated when a viewer-sinatra pull request is merged, but it would be better if it updated when a pull request was opened/updated so that the images are there ready before the data gets merged so Gender Balance doesn't show broken images.

**Comment by chrismytton** [comment]
As of https://github.com/everypolitician/viewer-sinatra/commit/721cffb811309e6bf41ab7e113794218d247ba15 the images get updated every time there is a travis build. However it will only pick up images for a new country once that country is merged to master.

**Comment by tmtmtmtm** [comment]
I disabled this as it was making the travis build take too long. Now that we don't get broken images from the proxy when they're not there yet, maybe we should just schedule this to rebuild all the images once (or more) per day, and we can supplement that with a manual run any time we need them quicker?

**Comment by chrismytton** [comment]
I've added a cronjob on my user account on firefly to run this daily and push the results back to GitHub.
