### ISSUE TITLE
Track usage of interactive page elements

### ISSUE THREAD

**Issue by zarino** [everypolitician/viewer-sinatra#5420]
We should use google analytics events to track how many people are using the interactive elements on the term page in particular.

Eg: do people spot the download button? Do people use the filter box? Do people use the person-card section toggle? Do people click party names at the top to filter by party? Do people navigate between terms using the Earlier/Later links, or the dropdown menu?

**Comment by ondenman** [comment]
Tracking events on term-table page:
[ ] Records user clicks on specified elements (PR #13334)
[ ] Records user clicks on links that navigation off page (PR #13334)
[ ] Records when drop down list is focussed (PR #13334)
[ ] Records user selection from drop down list
