### ISSUE TITLE
Make different card views bookmarkable/linkable

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#5611]
Currently, clicking on the toggles for different views of the Person cards doesn't change the URL, so the resulting view isn't bookmarkable, or directly linkable. It would be nice to be able to address these directly (presumably with URL fragments), and have switching between them update that.

![screen shot 2016-03-21 at 12 35 51](https://cloud.githubusercontent.com/assets/57483/13918816/84ed619e-ef61-11e5-9b36-bcee56f54985.png)

**Comment by zarino** [comment]
This was fixed by https://github.com/everypolitician/viewer-sinatra/commit/ef24de2b315e0bce37579120b1a67921e097966d
