### ISSUE TITLE
GLOW banner

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#575]
For [GLOW](http://openparlweek.org/), we're on a drive to get to 200 countries covered. @MyfanwyNixon has put together a blog post. @davewhiteland is writing some ['how you can help us with that'](https://github.com/everypolitician/viewer-sinatra/pull/574) pages. I've added a [simple page](http://everypolitician.org/needed.html) that lists all the outstanding countries.

We need a lead in paragraph for that page explaining what it is, and then a big banner for the front page, that links to it, saying something like "Destination 200 — Help us get to 200 countries during GLOW 2015!" Hopefully @zarino might have a few spare moments today to put something snazzy together for us for that, so that it's not just a big ugly text link? (Sorry that it's so last minute!)

**Comment by MyfanwyNixon** [comment]
I'll put the paragraph together this morning.
Incidentally, do we need an explanation of where the figure 200 comes from, given that a casual Google of 'how many countries are there' will yield 195 or 196?

**Comment by tmtmtmtm** [comment]
Thanks. A link to https://en.wikipedia.org/wiki/List_of_legislatures_by_country is probably enough somewhere

**Comment by MyfanwyNixon** [comment]
> This page lists the countries for which we don't yet have data, in two categories.

>  **Source needed** We need help finding reliable, current data. Click on any country to see the relevant Github ticket, where you can comment with any sources you've found.

> **Scraper needed** Countries where we have identified the data, but have not yet written the scraper that allows us to convert and import it. Click on any country to find the relevant Github ticket, where you'll see a link to the data we've found. Please comment if you intend to start work on a scraper. 


(Feel free to adjust my wording if I haven't got it quite right)

**Comment by tmtmtmtm** [comment]
For the first paragraph, I think we need something a little more detailed, to explain _what_ we need them to find. Whether that's in-place here, or somewhere else, I'm not sure. @davewhiteland was hopefully going to be writing something about this, but maybe we just need a simplified version here first so we can put it live and evolve?

**Comment by zarino** [comment]
There's a PR here with the homepage banner, just waiting a URL for the blog post from @davewhiteland:

https://github.com/everypolitician/viewer-sinatra/issues/579

You can re-use the same yellow-background-with-icons styling for the "needed" page etc, if you want. Just use `<div class="hero hero--destination-500"></div>` once that branch has been merged.

**Comment by tmtmtmtm** [comment]
Closed by #579
