### ISSUE TITLE
explain composite column when saving in scraper

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/viewer-sinatra#577]
Need to explain when you might want to use a composite column group on the save (i.e. there will be more than one record per person, such as if you're scraping multiple terms).

**Comment by davewhiteland** [comment]
@tmtmtmtm is this covered by the table spanning terms in http://everypolitician.org/submitting.html ?

**Comment by tmtmtmtm** [comment]
@davewhiteland This was your ticket initially, but I assumed it was about explaining that you'd need to have an array of `unique_keys` in the `save_sqlite` call in your scraper, as otherwise, if you only keyed on `id`, for example, the second row would simply clobber the first…

**Comment by tmtmtmtm** [comment]
moved to https://github.com/everypolitician/everypolitician-docs/issues/14
