### ISSUE TITLE
Text and Image overlapping in header

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#596]
I don't know how to replicate this, but from time to time some glitch means that the EveryPolitician in my header bar gets doubled with both a text and the image:

![screen shot 2015-09-08 at 07 08 36](https://cloud.githubusercontent.com/assets/57483/9727620/95e85ec0-55f8-11e5-8d91-b0d600a7a2d8.png)

(Chrome, latest)

**Comment by zarino** [comment]
@tmtmtmtm Have you seen this recently? Because I can’t replicate it.

**Comment by tmtmtmtm** [comment]
not in a while, so I'll close it for now, and reopen if it reappears.
