### ISSUE TITLE
Identifier labels on person cards are overlapping with values

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/viewer-sinatra#6274]
Originally ticketed in https://github.com/everypolitician/everypolitician/issues/369 by @paullenz.

![screenshot 2016-03-29 16 32 08](https://cloud.githubusercontent.com/assets/909811/14113718/15b117b4-f5cc-11e5-9526-c3d9ebcbd5c9.png)

Viewed  in Safari

e.g. on the identifier section of http://everypolitician.org/uk/commons/term-table/56.html

**Comment by zarino** [comment]
Pains me to say, but maybe we just use a table here, instead of a list. (It'll look the same, but the "columns" will stretch to fit their content)

Relatively quick change to make.
