### ISSUE TITLE
Document the need for a `source` column

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#683]
All rows should include a `source` URL

**Comment by davewhiteland** [comment]
@tmtmtmtm clarification please: if individual person's data is coming from a page for that person, this is clear; but if data is coming from a page that contains lots of people, including this one, should that collective URL appear as the source for this individual? (I think "yes", but I'm not sure).

Also, for multiple sources, comma separated or just limit this to one URL?

**Comment by tmtmtmtm** [comment]
It should be the best source for that row of data. If that's from a page just about that person — great. If it's from a list on a page with lots of people, then yep, use that.

> for multiple sources, comma separated or just limit this to one URL?

A row should really only have one source. If there are multiple sources, then it should come in as multiple rows that will end up getting joined together. This is probably worth documenting separately (if you're scraping multiple sites, write individual scrapers for each, and let us combine them)
