### ISSUE TITLE
Use access token rather than ssh key in release.sh

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/viewer-sinatra#711]
As described in https://gist.github.com/domenic/ec8b0fc8ab45f39403dd this seems like a simpler approach than having to [mess around decrypting ssh keys and starting the ssh agent](https://github.com/everypolitician/viewer-sinatra/blob/570a8a7e4238616c931e83de3c6405d8ab2cca0a/scripts/release.sh#L7-L12).

**Comment by tmtmtmtm** [comment]
@chrismytton is this still an issue with the new approach?

**Comment by chrismytton** [comment]
Yes, we're still [using ssh keys rather than access tokens](https://github.com/everypolitician/viewer-sinatra/blob/0d00ec428f82c1ec72f790fc7a4662235a8fd1b6/scripts/release.sh#L7-L12), but TBH I don't think it's really a problem. If it ain't broke etc…

Closing this as it's not a problem.

**Comment by chrismytton** [comment]
I think this will be useful as part of [changing the way everypolitician.org is deployed](https://github.com/everypolitician/everypolitician/projects/2). Supplying an access token in `.travis.yml` is _so_ much easier than having to decrypt and load an SSH key.
