### ISSUE TITLE
Remove GLOW banner?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#722]
We should probably remove this at some point quite soon, though it would still be nice to mention _something_ about it somewhere.

**Comment by zarino** [comment]
Well, even if we get rid of the one on the homepage, there's still the same banner on the "Contribute" page – we could leave that there?

![screen shot 2015-10-08 at 16 51 45](https://cloud.githubusercontent.com/assets/739624/10371820/02200cc2-6ddd-11e5-9d8c-54a29b7ef89d.png)

**Comment by tmtmtmtm** [comment]
I guess so, though even there it seems disproportionately prominent now…

**Comment by zarino** [comment]
For now I’m just going to remove the banners. You can decide with @MyfanwyNixon as to how you want to work a mention of GLOW into the site – if you still do.

**Comment by MyfanwyNixon** [comment]
Personally I think the moment has passed now!
