### ISSUE TITLE
allow other CSV columns to be displayed on data pages

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/viewer-sinatra#945]
Currently we're only showing 4 (or so) columns, but we should be communicating that others are also available (e.g., twitter, date of birth etc). It's limited to four to make the data nice and clear on the page (not too crowded).

Add a "More columns" column header/widget that lets user choose from the list of other columns, and reveal them appropriately.

**Comment by zarino** [comment]
Closed by https://github.com/everypolitician/viewer-sinatra/commit/5b7a3b4b6c5a23cfa182e0ae4a1ecd0d1480ed20
